### ISSUE TITLE
fix ci

### ISSUE THREAD

**Issue by aerickson** [mozilla-platform-ops/ronin_puppet#365]
Tests went red between b04d1d3e5744fe7171f09a48bbe3d87b7de9c848 and cce92c445388eac706f3ddba3fe63477ec4277b7.

Not sure how this happened (I didn't update the lock file in my #361) and my test run was green.

error:

```ruby
-----> Installing bundler via rubygems
Fetching: bundler-2.2.30.gem (100%)
       Successfully installed bundler-2.2.30
       1 gem installed
       ---> BUNDLE_CMD variable is: /usr/local/bin/bundle
       Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
       installing your bundle as root will break this application for all non-root
       users on this machine.
       Fetching gem metadata from https://rubygems.org/....
       Resolving dependencies...
       Using bundler 2.2.30
       Fetching diff-lcs 1.4.4
       Fetching multi_json 1.15.0
       Installing multi_json 1.15.0
       Installing diff-lcs 1.4.4
       Fetching net-ssh 3.2.0
       Installing net-telnet 0.1.1
       Fetching rspec-support 3.10.2
       Installing rspec-support 3.10.2
       Fetching sfl 2.3
       Installing net-ssh 3.2.0
       Installing sfl 2.3
       Fetching rspec-core 3.10.1
       Installing rspec-core 3.10.1
       Fetching rspec-expectations 3.10.1
       Fetching rspec-mocks 3.10.2
       Installing rspec-expectations 3.10.1
       Installing rspec-mocks 3.10.2
       Fetching net-scp 3.0.0
       Fetching rspec-its 1.3.0
       Installing net-scp 3.0.0
       Installing rspec-its 1.3.0
       Fetching rspec 3.10.0
       Installing rspec 3.10.0
       Bundler::GemNotFound: Could not find net-telnet-0.1.1.gem for installation
        
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/source/rubygems.rb:177:in
       `install'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/installer/gem_installer.rb:54:in
       `install'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/installer/gem_installer.rb:16:in
       `install_from_spec'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/installer/parallel_installer.rb:186:in
       `do_install'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/installer/parallel_installer.rb:177:in
       `block in worker_pool'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/worker.rb:62:in
       `apply_func'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/worker.rb:57:in `block in
       process_queue'
         /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/worker.rb:54:in `loop'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/worker.rb:54:in
       `process_queue'
       /var/lib/gems/2.5.0/gems/bundler-2.2.30/lib/bundler/worker.rb:91:in `block (2
       levels) in create_threads'
       
       An error occurred while installing net-telnet (0.1.1), and Bundler
       cannot continue.
       
       In Gemfile:
         serverspec was resolved to 2.41.8, which depends on
           specinfra was resolved to 2.83.1, which depends on
             net-telnet
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [SSH exited (5) for command: [            
            if [ ! $(which ruby) ]; then
              echo '-----> Installing ruby, will try to determine platform os'
              if [ -f /etc/centos-release ] || [ -f /etc/redhat-release ] || [ -f /etc/oracle-release ]; then
                sudo -E -H yum -y install ruby
              else
                if [ -f /etc/system-release ] && grep -q 'Amazon Linux' /etc/system-release; then
                  sudo -E -H yum -y install ruby
                else
                  sudo -E -H apt-get -y update
                  sudo -E -H apt-get -y install ruby
                fi
              fi
            fi
                        if [ -f /etc/centos-release ] || [ -f /etc/redhat-release ] || [ -f /etc/oracle-release ]; then
              echo '-----> Installing os provided bundler package'
              sudo -E -H yum -y install rubygem-bundler
            else
              echo '-----> Installing bundler via rubygems'
              if [ "$(sudo -E -H gem list bundler -i)" = "true" ]; then
                echo "Bundler already installed"
              else
                if [ "$(sudo -E -H gem list bundler -i)" = "false" ]; then
                  sudo -E -H gem install  --no-ri --no-rdoc bundler
                else
                  echo "ERROR: Ruby not installed correctly"
                  exit 1
                fi
              fi
            fi

            if [ -d /tmp/kitchen ]; then
                            if [ "$(sudo -E -H gem list serverspec -i)" = "false" ]; then
                        sudo -E -H rm -f /tmp/kitchen/Gemfile
          sudo -E -H echo "source 'https://rubygems.org'" >> /tmp/kitchen/Gemfile
          sudo -E -H echo "gem 'net-ssh','~> 3'"  >> /tmp/kitchen/Gemfile
          sudo -E -H echo "gem 'serverspec'" >> /tmp/kitchen/Gemfile

              BUNDLE_CMD=$(which bundle)
              echo "---> BUNDLE_CMD variable is: ${BUNDLE_CMD}"
              sudo -E -H  $BUNDLE_CMD install --gemfile=/tmp/kitchen/Gemfile
            fi

              
            else
              echo "ERROR: Default path '/tmp/kitchen' does not exist"
              exit 1
            fi
]] on linux-ubuntu-1804
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration


Exited with code exit status 20


```

**Comment by aerickson** [comment]
Appears to be due to a change in bundler. The serverspec verifier installs the latest version and something changed in v2.2.30 (particularly rubygems/rubygems#4974) per my research in https://github.com/aerickson/test_kitchen_docker_serverspec_bug_demo.

**Comment by aerickson** [comment]
Inspec doesn't seem to have the problem and offers advantages to ServerSpec (can inspect more things, the things it is missing we don't use). We can keep using both (syntax is very similar).

I'll start on a PR porting the linux tests (what's currently failing) to InSpec.

**Comment by aerickson** [comment]
Setting remote_exec to false with the current verifier also makes this work in my test repo, but in ronin-puppet there are many errors.

```
verifier:
  name: serverspec
  default_pattern: true
  remote_exec: false
```
